// filters.ts

export const ERP_FILTERS = {
    OFICINA: 3,
    USUARIO: 4,

    ASESORIA_OFICINA: 18,
    ASESORIA_USUARIO: 19,
    ASESORIA_MODULO: 20,
    ASESORIA_OPERACION: 21,

    BANNER_USUARIO: 22,

    FECHA_ASESORIA: -2,
    FECHA_BANNER: -3,
    FECHA_AUTENTICACION: -4
};