export const Estados = {
    Abogado: '1',
    Activa: '5',
    Anulada: '10',
    Aprobado: '15',
    AprobadoRetiro: '16',
    Autorizado: '18',
    Bloqueado: '20',
    Cancelado: '25',
    Castigado: '26',
    Recuperado: '27',
    Contraordenado: '28',
    Devuelto: '29',
    Embargada: '30',
    Entregado: '31',
    Fallecido: '32',
    Generado: '33',
    InactivoDGTN: '36',
    Liquidado: '37',
    Ley550: '38',
    Moroso: '40',
    Negado: '42',
    NoTomado: '43',
    Nueva: '45',
    Desembolsado: '46',
    Pendiente: '47',
    PendienteRetiro: '48',
    Pignorada: '50',
    Prejurídico: '51',
    Preliquidado: '52',
    Radicado: '53',
    Retirada: '55',
    RetiradoConSaldo: '57',
    Saldada: '60',
    SolicitudDeRetiro: '65',
    Vencido: '68',
    Verificado: '70',

    /* Estados gestion operaciones */
    GO_Cancelada: '5544',
    GO_Gestionada: '5543',
    GO_Pendiente: '5542',
    GO_Rechazada: '5546'
    /*Fin Estados gestion operaciones */
};
